name: NoCreeperExplosion
version: ${project.version}
main: me.lolnypop.noCreeperExplosion.NoCreeperExplosion
api-version: 1.21

author: lolnypop
description: Provides options to configure creeper behaviors in your world.

commands:
  nocreeperexplosion:
    description: Reloads the configuration file of the NoCreeperExplosion plugin.
    usage: /nocreeperexplosion reload

  permissions:
    nocreeperexplosion.reload:
      description: Allows the player to reload the NoCreeperExplosion plugin's configuration file.
      default: op